create table note
    (id int8 generated by default as identity,
    content varchar(255),
    date_time timestamp,
    position int4 not null,
    status varchar(255),
    person_id int8,
    primary key (id));

create table person
    (id int8 generated by default as identity,
    name varchar(255),
    password varchar(255),
    primary key (id));

alter table if exists note
    add constraint fk1 foreign key (person_id) references person;